#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const desktopDir = resolve(scriptDir, "..");
const tauriDir = resolve(desktopDir, "src-tauri");
const cargoTomlPath = resolve(tauriDir, "Cargo.toml");
const cargoLockPath = resolve(tauriDir, "Cargo.lock");
const ninjaDir = resolve(desktopDir, ".cef-tools", "ninja");
const ninjaExe = resolve(ninjaDir, process.platform === "win32" ? "ninja.exe" : "ninja");

const patchStart = "# BEGIN CEF PATCH - generated by scripts/cef-patch.mjs";
const patchEnd = "# END CEF PATCH";
const cefFeatureLine = 'cef = ["tauri/cef"]';
const tauriGit = "https://github.com/tauri-apps/tauri";

const patchBlock = `${patchStart}
[patch.crates-io]
tauri = { git = "${tauriGit}", branch = "feat/cef" }
tauri-build = { git = "${tauriGit}", branch = "feat/cef" }
${patchEnd}`;

function readCargoToml() {
  return readFileSync(cargoTomlPath, "utf8");
}

function writeCargoToml(contents) {
  writeFileSync(cargoTomlPath, contents);
}

function removeCefPatch(contents) {
  const patchPattern = new RegExp(
    `\\r?\\n?${escapeRegExp(patchStart)}[\\s\\S]*?${escapeRegExp(patchEnd)}\\r?\\n?`,
    "m"
  );

  return `${contents
    .replace(patchPattern, "\n")
    .replace(/^\s*cef\s*=\s*\["tauri\/cef"\]\s*\r?\n?/m, "")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}

function addCefPatch(contents) {
  let next = removeCefPatch(contents);

  if (!/^\[features\]\s*$/m.test(next)) {
    next = next.replace(
      /^(\[build-dependencies\]\s*)$/m,
      `[features]\ndefault = ["tauri-wry"]\ntauri-wry = ["tauri/wry"]\n\n$1`
    );
  }

  if (!new RegExp(`^\\s*${escapeRegExp(cefFeatureLine)}\\s*$`, "m").test(next)) {
    if (/^tauri-wry\s*=\s*\["tauri\/wry"\]\s*$/m.test(next)) {
      next = next.replace(/^(tauri-wry\s*=\s*\["tauri\/wry"\]\s*)$/m, `$1\n${cefFeatureLine}`);
    } else {
      next = next.replace(/^(\[features\]\s*)$/m, `$1\n${cefFeatureLine}`);
    }
  }

  if (/^\[patch\.crates-io\]\s*$/m.test(next)) {
    throw new Error("Cargo.toml already contains [patch.crates-io]; merge the CEF patch manually.");
  }

  return `${next.trimEnd()}\n\n${patchBlock}\n`;
}

function patchCargoToml() {
  writeCargoToml(addCefPatch(readCargoToml()));
}

function cleanupCargoToml() {
  writeCargoToml(removeCefPatch(readCargoToml()));
}

function readCargoLock() {
  return existsSync(cargoLockPath) ? readFileSync(cargoLockPath, "utf8") : null;
}

function restoreCargoLock(contents) {
  if (contents !== null) {
    writeFileSync(cargoLockPath, contents);
  }
}

function updateCefLockfile(env) {
  return spawnSync("cargo", ["update", "-p", "tauri", "-p", "tauri-build"], {
    cwd: tauriDir,
    env,
    shell: false,
    stdio: "inherit",
  });
}

function ensureBuildTools(commandArgs) {
  const env = { ...process.env };
  const isMetadataOnly = commandArgs[0] === "cargo" && commandArgs[1] === "metadata";

  if (isMetadataOnly) {
    return env;
  }

  if (commandExists("ninja", ["--version"], env)) {
    return env;
  }

  if (process.platform !== "win32") {
    throw new Error(
      "CEF builds require Ninja. Install ninja-build and make sure `ninja` is available in PATH."
    );
  }

  if (!existsSync(ninjaExe)) {
    downloadWindowsNinja();
  }

  const delimiter = process.platform === "win32" ? ";" : ":";
  env.PATH = `${ninjaDir}${delimiter}${env.PATH ?? ""}`;
  env.Path = env.PATH;

  return env;
}

function commandExists(command, args, env) {
  const result = spawnSync(command, args, {
    env,
    shell: false,
    stdio: "ignore",
  });

  return result.status === 0;
}

function downloadWindowsNinja() {
  const ninjaZip = resolve(ninjaDir, "ninja-win.zip");
  const ninjaUrl = "https://github.com/ninja-build/ninja/releases/download/v1.13.1/ninja-win.zip";
  const command = [
    "$ErrorActionPreference = 'Stop'",
    `$zip = ${powerShellString(ninjaZip)}`,
    `$dest = ${powerShellString(ninjaDir)}`,
    "New-Item -ItemType Directory -Force -Path $dest | Out-Null",
    `Invoke-WebRequest -UseBasicParsing -Uri ${powerShellString(ninjaUrl)} -OutFile $zip`,
    "Expand-Archive -Force -Path $zip -DestinationPath $dest",
  ].join("; ");

  console.log("Ninja was not found in PATH. Downloading a local Ninja build for CEF...");

  const result = spawnSync(
    "powershell",
    ["-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", command],
    {
      cwd: desktopDir,
      env: process.env,
      shell: false,
      stdio: "inherit",
    }
  );

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function powerShellString(value) {
  return `'${value.replaceAll("'", "''")}'`;
}

function withCefArgs(args) {
  const separatorIndex = args.indexOf("--");
  const beforeCargoArgs = separatorIndex === -1 ? [...args] : args.slice(0, separatorIndex);
  const cargoArgs = separatorIndex === -1 ? [] : args.slice(separatorIndex + 1);

  const commandIndex = beforeCargoArgs.findIndex((arg, index) => {
    return (arg === "dev" || arg === "build") && beforeCargoArgs[index - 1] === "tauri";
  });

  if (commandIndex === -1) {
    const nextArgs = [...beforeCargoArgs];
    if (!nextArgs.includes("--no-default-features")) {
      nextArgs.push("--no-default-features");
    }
    if (!hasFeature(nextArgs, "cef")) {
      nextArgs.push("--features", "cef");
    }
    return nextArgs;
  }

  if (!hasFeature(beforeCargoArgs, "cef")) {
    beforeCargoArgs.splice(commandIndex + 1, 0, "--features", "cef");
  }

  const nextCargoArgs = [...cargoArgs];
  if (!nextCargoArgs.includes("--no-default-features")) {
    nextCargoArgs.unshift("--no-default-features");
  }
  if (!hasFeature(nextCargoArgs, "cef")) {
    nextCargoArgs.push("--features", "cef");
  }

  return [...beforeCargoArgs, "--", ...nextCargoArgs];
}

function hasFeature(args, feature) {
  return args.some((arg, index) => {
    if (arg === "--features" || arg === "-F") {
      return args[index + 1]?.split(",").includes(feature);
    }
    return arg === `--features=${feature}` || arg === `-F${feature}`;
  });
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

const [, , command, ...rest] = process.argv;

if (!command || command === "help" || command === "--help") {
  console.log("Usage: node scripts/cef-patch.mjs cleanup | <command...>");
  process.exit(command ? 0 : 1);
}

if (command === "cleanup") {
  cleanupCargoToml();
  console.log("Removed temporary CEF Cargo patch.");
  process.exit(0);
}

const commandArgs = withCefArgs([command, ...rest]);
const cargoLockBackup = readCargoLock();
let result;
const commandCwd = commandArgs[0] === "cargo" && commandArgs[1] !== "tauri" ? tauriDir : desktopDir;
const commandEnv = ensureBuildTools(commandArgs);

try {
  patchCargoToml();
  const updateResult = updateCefLockfile(commandEnv);

  if (updateResult.error || updateResult.status !== 0 || updateResult.signal) {
    result = updateResult;
  } else {
    result = spawnSync(commandArgs[0], commandArgs.slice(1), {
      cwd: commandCwd,
      env: commandEnv,
      shell: false,
      stdio: "inherit",
    });
  }
} finally {
  cleanupCargoToml();
  restoreCargoLock(cargoLockBackup);
}

if (result.error) {
  throw result.error;
}

if (result.signal) {
  process.kill(process.pid, result.signal);
}

process.exit(result.status ?? 1);
